{
const svg=(p)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`;
const icons={
home:svg('<path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/>'),
library:svg('<path d="M4 19.5V5a2 2 0 0 1 2-2h12v16H6a2 2 0 0 0 0 4h12"/><path d="M8 7h6"/>'),
calendar:svg('<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>'),
users:svg('<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>'),
moon:svg('<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>'),plus:svg('<path d="M12 5v14M5 12h14"/>'),play:svg('<path d="m7 4 13 8-13 8Z"/>'),
link:svg('<path d="M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7-7L12 5"/><path d="M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7 7l1.5-1.5"/>'),
clock:svg('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'),search:svg('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'),
left:svg('<path d="m15 18-6-6 6-6"/>'),right:svg('<path d="m9 18 6-6-6-6"/>'),check:svg('<path d="m5 12 4 4L19 6"/>'),
settings:svg('<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A8 8 0 0 0 15 6l-.3-2.6h-4L10.4 6A8 8 0 0 0 9 7L6.5 6l-2 3.4L6.6 11a7 7 0 0 0 0 2l-2.1 1.6 2 3.4L9 17a8 8 0 0 0 1.4 1l.3 2.6h4L15 18a8 8 0 0 0 1.5-1l2.4 1 2-3.4-2-1.5c.1-.4.1-.7.1-1.1Z"/>'),
history:svg('<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>'),archive:svg('<rect x="3" y="4" width="18" height="4" rx="1"/><path d="M5 8v12h14V8M10 12h4"/>'),mail:svg('<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>'),more:svg('<circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/>')};
const schemes=[{id:'air',name:'Air · 蓝灰',desc:'已选主设计 · 清晰克制',tag:'已选择'},{id:'cinema',name:'Air · 黑金',desc:'同一结构 · 影院配色',tag:'可切换'},{id:'together',name:'Air · 暖杏',desc:'同一结构 · 关系配色',tag:'可切换'}];
let currentPage='home',currentTheme='light',currentPalette='air';
const statusbar=()=>`<div class="status-pill"></div><div class="statusbar"><span>9:41</span><span class="system-icons"><svg viewBox="0 0 18 12"><path d="M1 10h2M5 8h2M9 5h2M13 2h2"/></svg><svg viewBox="0 0 16 12"><path d="M2 4.5a9 9 0 0 1 12 0M4.5 7a5.5 5.5 0 0 1 7 0M7 9.5a2 2 0 0 1 2 0"/></svg><svg viewBox="0 0 22 12"><rect x="1" y="1" width="17" height="10" rx="2"/><path d="M20 4v4"/><path d="M3.5 3.5h11v5h-11Z" fill="currentColor" stroke="none"/></svg></span></div>`;
const nav=(active)=>`<nav class="bottom-nav">${[['home','首页',icons.home],['library','片库',icons.library],['calendar','日历',icons.calendar],['us','我们',icons.users]].map(([id,label,icon])=>`<button class="nav-item ${active===id?'active':''}" data-nav="${id}">${icon}<span>${label}</span></button>`).join('')}</nav>`;
const themeButton=()=>`<button class="icon-button ghost theme-local" aria-label="切换主题">${icons.moon}</button>`;
const top=(title,eyebrow,action=themeButton())=>`<header class="page-head"><div><div class="eyebrow">${eyebrow}</div><h2 class="page-title">${title}</h2></div>${action}</header>`;
const relationship=()=>`<div class="card relationship"><div class="avatar-pair"><span class="avatar">梅</span><span class="avatar">然</span></div><div class="relationship-main"><div class="relationship-title">小梅和阿然</div><div class="relationship-sub">已绑定 128 天 · <span style="color:var(--success)">双方在线</span></div></div><span class="badge success"><i class="dot"></i>在线</span></div>`;
const planRows=()=>`<div><div class="row"><div class="row-icon">${icons.clock}</div><div class="row-main"><div class="row-title">20:00 · 星际穿越</div><div class="row-sub">吃完饭一起看</div></div><span class="chev">›</span></div><div class="row"><div class="row-icon">${icons.play}</div><div class="row-main"><div class="row-title">当天 · 旅行纪录片</div><div class="row-sub">来自共享片库</div></div><span class="chev">›</span></div></div>`;
function airHome(){return `<div class="content scroll">${top('你们的空间','今天，8月11日')}${relationship()}<div class="button-row" style="margin-top:12px"><button class="button primary js-watch">${icons.play}<span>开始同看</span></button><button class="button outline js-toast">${icons.link}<span>加入房间</span></button></div><div class="section-row"><span class="section-title">今天想看</span><span class="section-meta">2 个计划</span></div>${planRows()}<div class="section-row"><span class="section-title">这个月</span><span class="section-meta">有效同看</span></div><div class="metrics"><div class="metric"><strong>6.8h</strong><span>共同观看</span></div><div class="metric"><strong>9</strong><span>完成视频</span></div><div class="metric"><strong>4</strong><span>观看计划</span></div></div></div>${nav('home')}${sheet('创建同看房间')}${toast()}`}
function cinemaHome(){return `<div class="content scroll">${top('今晚看什么','小梅和阿然 · 在线')}<div class="hero-media"><div class="hero-copy"><div class="hero-kicker">今晚 20:00 · 已计划</div><div class="hero-title">星际穿越</div></div><div class="hero-actions"><button class="button primary js-watch">${icons.play}<span>开始同看</span></button><button class="icon-button js-toast">${icons.more}</button></div></div><div class="section-row"><span class="section-title">接下来</span><span class="section-meta">本月一起看了 6.8 小时</span></div><div class="card card-pad"><div class="media-row"><div class="mini-poster alt"></div><div class="row-main"><div class="row-title">旅行纪录片</div><div class="row-sub">当天 · 未观看</div></div><span class="badge">纪录片</span></div><div class="media-row"><div class="mini-poster warm"></div><div class="row-main"><div class="row-title">动画短片集</div><div class="row-sub">周六 · 阿然添加</div></div><span class="badge">动画</span></div></div></div>${nav('home')}${sheet('创建同看房间')}${toast()}`}
function togetherHome(){return `<div class="content scroll">${top('今天','两个人的观影日记')}<div class="card elevated card-pad"><div class="card-head"><div><div class="card-title">在一起看的第 128 天</div><div class="card-desc"><span style="color:var(--success)">●</span> 阿然现在在线</div></div><div class="avatar-pair"><span class="avatar">梅</span><span class="avatar">然</span></div></div><div style="height:1px;margin:15px 0;background:linear-gradient(90deg,#5b7cfa,#ff8a7c)"></div><div class="card-desc">这个月已经一起看了 6 小时 48 分钟</div></div><div class="section-row"><span class="section-title">今晚的约定</span><span class="section-meta">8月11日 · 20:00</span></div><div class="card card-pad"><div class="card-title">一起看《星际穿越》</div><div class="card-desc">吃完饭一起看 · 来自共享片库</div><div class="button-row" style="margin-top:14px"><button class="button primary js-watch">${icons.play}<span>开始同看</span></button><button class="button outline js-sheet">换一个</button></div></div><div class="section-row"><span class="section-title">最近的我们</span><span class="section-meta">共同记忆</span></div><div class="timeline"><div class="timeline-item"><div class="timeline-time">昨天</div><div class="timeline-title">一起看完了《宇宙时空之旅》</div></div><div class="timeline-item"><div class="timeline-time">这个月</div><div class="timeline-title">共同观看 6 小时 48 分钟</div></div></div></div>${nav('home')}${sheet('从片库换一个')}${toast()}`}
function login(s){const intro=s==='cinema'?'把今晚留给同一部电影。':s==='together'?'两个人的片单、计划和回忆，都在这里。':'登录后，继续你们的共享片库与观看记录。';return `<div class="auth-shell"><div class="brand-mark">同看</div><h2 class="auth-title">欢迎回来</h2><p class="auth-copy">${intro}</p><div class="auth-form"><div class="field"><label>邮箱</label><input type="email" inputmode="email" placeholder="name@example.com" value="xiaomei@example.com"><div class="field-help">验证码会发送到这个邮箱，10 分钟内有效。</div></div><button class="button primary full js-code">${icons.mail}<span>获取验证码</span></button><button class="button outline full js-toast">暂时使用匿名房间</button></div><p class="auth-note">继续即表示同意仅将账号用于同步观看与双人空间。<br><button class="link-button js-toast">了解数据如何保存</button></p></div>${sheet('邮箱登录说明')}${toast()}`}
const mediaItems=()=>`<div class="media-row"><div class="mini-poster"></div><div class="row-main"><div class="row-title">星际穿越</div><div class="row-sub">电影 · 今天 20:00</div></div><button class="icon-button ghost js-toast">${icons.more}</button></div><div class="media-row"><div class="mini-poster alt"></div><div class="row-main"><div class="row-title">旅行纪录片</div><div class="row-sub">纪录片 · 未观看</div></div><button class="icon-button ghost js-toast">${icons.more}</button></div><div class="media-row"><div class="mini-poster warm"></div><div class="row-main"><div class="row-title">动画短片集</div><div class="row-sub">动画 · 阿然添加</div></div><button class="icon-button ghost js-toast">${icons.more}</button></div>`;
function libraryPage(s){return `<div class="content scroll">${top(s==='cinema'?'继续挑选':'片库','完全共享',`<button class="icon-button js-sheet" aria-label="添加视频">${icons.plus}</button>`)}<div class="stack"><div class="search-field"><span class="field-icon">${icons.search}</span><input type="search" placeholder="搜索共享片库"></div><div class="tabs"><button class="tab active">全部 18</button><button class="tab">未观看 8</button><button class="tab">已计划 4</button><button class="tab">已看完 6</button></div></div><div class="section-row"><span class="section-title">全部视频</span><span class="section-meta">最近更新</span></div><div class="card card-pad">${mediaItems()}</div></div>${nav('library')}${sheet('添加到共享片库')}${toast()}`}
const dates=['28','29','30','31','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31'];
function calendarPage(){return `<div class="content scroll">${top('日历','计划与共同记录',`<button class="icon-button js-sheet" aria-label="新增计划">${icons.plus}</button>`)}<div class="card calendar-card"><div class="calendar-head"><span class="month">2026年 8月</span><div class="calendar-nav"><button class="icon-button ghost">${icons.left}</button><button class="icon-button ghost">${icons.right}</button></div></div><div class="week"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div class="dates">${dates.map((d,i)=>`<div class="date ${i<4?'dim':''} ${d==='11'?'active':([7,15,25].includes(i)?'plan':'')}">${d}</div>`).join('')}</div></div><div class="section-row"><span class="section-title">8月11日</span><span class="section-meta">2 个计划</span></div><div class="timeline"><div class="timeline-item"><div class="timeline-time">20:00</div><div class="timeline-title">星际穿越</div><div class="timeline-note">吃完饭一起看</div></div><div class="timeline-item"><div class="timeline-time">当天</div><div class="timeline-title">旅行纪录片</div><div class="timeline-note">未设置具体时间</div></div></div></div>${nav('calendar')}${sheet('新增观看计划')}${toast()}`}
function usPage(){return `<div class="content scroll">${top('我们','小梅和阿然')}<div class="profile-hero"><div class="avatar-pair"><span class="avatar large">梅</span><span class="avatar large">然</span></div><div class="profile-title">已经一起 128 天</div><div class="profile-sub"><span style="color:var(--success)">●</span> 双方在线</div></div><div class="metrics" style="margin-top:12px"><div class="metric"><strong>26.4h</strong><span>累计同看</span></div><div class="metric"><strong>32</strong><span>看完视频</span></div><div class="metric"><strong>18</strong><span>共享片库</span></div></div><div class="section-row"><span class="section-title">共同空间</span><span class="section-meta">只对你们可见</span></div><div class="card card-pad"><div class="row js-toast"><div class="row-icon">${icons.history}</div><div class="row-main"><div class="row-title">共同观看历史</div><div class="row-sub">按月份回顾看过的内容</div></div><span class="chev">›</span></div><div class="row js-toast"><div class="row-icon">${icons.archive}</div><div class="row-main"><div class="row-title">过去的双人空间</div><div class="row-sub">只读归档与保留选择</div></div><span class="chev">›</span></div><div class="row js-toast"><div class="row-icon">${icons.settings}</div><div class="row-main"><div class="row-title">账号与设置</div><div class="row-sub">头像、主题、退出登录</div></div><span class="chev">›</span></div></div><div class="danger-zone"><button class="button destructive full js-toast">解除好友绑定</button></div></div>${nav('us')}${sheet('账号与空间设置')}${toast()}`}
function sheet(title){return `<div class="sheet-backdrop js-close-sheet"></div><section class="sheet" role="dialog" aria-modal="true"><div class="sheet-handle"></div><div class="sheet-title">${title}</div><p class="sheet-copy">使用底部抽屉完成补充操作，不打断当前页面，也避免把所有功能藏进右上角菜单。</p><div class="sheet-form"><div class="field"><label>视频链接或备注</label><input placeholder="粘贴 B站链接或输入内容"></div><div class="button-row"><button class="button outline js-close-sheet">取消</button><button class="button primary js-confirm-sheet">确认</button></div></div></section>`}
const toast=()=>`<div class="toast">${icons.check}<span>操作已收到，界面反馈清晰可见</span></div>`;
function pageFor(s){if(currentPage==='login')return login(s);if(currentPage==='library')return libraryPage(s);if(currentPage==='calendar')return calendarPage();if(currentPage==='us')return usPage();return airHome()}
function showToast(screen,message){const item=screen.querySelector('.toast');item.querySelector('span').textContent=message;item.classList.add('show');clearTimeout(item._timer);item._timer=setTimeout(()=>item.classList.remove('show'),1600)}
function runButtonState(btn,loading,done){if(btn.disabled)return;const span=btn.querySelector('span'),old=span.textContent;btn.disabled=true;btn.insertAdjacentHTML('afterbegin','<i class="spinner"></i>');span.textContent=loading;setTimeout(()=>{btn.querySelector('.spinner')?.remove();span.textContent=done;btn.disabled=false;showToast(btn.closest('.screen'),done);setTimeout(()=>span.textContent=old,1400)},850)}
function bind(root){
root.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.nav;sync();render()});
root.querySelectorAll('.theme-local').forEach(b=>b.onclick=()=>{currentTheme=currentTheme==='light'?'dark':'light';sync();render()});
root.querySelectorAll('.js-sheet').forEach(b=>b.onclick=()=>b.closest('.screen').classList.add('sheet-open'));
root.querySelectorAll('.js-close-sheet').forEach(b=>b.onclick=()=>b.closest('.screen').classList.remove('sheet-open'));
root.querySelectorAll('.js-confirm-sheet').forEach(b=>b.onclick=()=>{const s=b.closest('.screen');s.classList.remove('sheet-open');showToast(s,'已保存到两个人的空间')});
root.querySelectorAll('.js-toast').forEach(b=>b.onclick=()=>showToast(b.closest('.screen'),'操作已收到，界面反馈清晰可见'));
root.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
root.querySelectorAll('.js-watch').forEach(b=>b.onclick=()=>runButtonState(b,'正在创建房间…','房间已创建'));
root.querySelectorAll('.js-code').forEach(b=>b.onclick=()=>runButtonState(b,'发送中…','验证码已发送'));
}
function render(){const root=document.getElementById('compare'),s=schemes.find(item=>item.id===currentPalette)||schemes[0];root.innerHTML=`<section class="option"><div class="option-head"><div><div class="option-name">${s.name}</div><div class="option-desc">${s.desc}</div></div><span class="option-tag">${s.tag}</span></div><div class="device-wrap"><div class="phone ${s.id}"><div class="screen">${statusbar()}${pageFor(s.id)}</div></div></div></section>`;document.getElementById('studio').classList.toggle('dark-mode',currentTheme==='dark');bind(root)}
function sync(){document.querySelectorAll('#pageSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));document.querySelectorAll('#paletteSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.palette===currentPalette));document.querySelectorAll('#themeSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.theme===currentTheme))}
document.querySelectorAll('#pageSwitch button').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;sync();render()});document.querySelectorAll('#paletteSwitch button').forEach(b=>b.onclick=()=>{currentPalette=b.dataset.palette;sync();render()});document.querySelectorAll('#themeSwitch button').forEach(b=>b.onclick=()=>{currentTheme=b.dataset.theme;sync();render()});
const params=new URLSearchParams(location.search);if(params.get('page'))currentPage=params.get('page');if(params.get('palette'))currentPalette=params.get('palette');if(params.get('theme'))currentTheme=params.get('theme');sync();render();
}
